name: CI

on:
  push: # Triggers on pushes to all branches
  pull_request: # Triggers on pull requests to all branches

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive' # To ensure thirdparty/quik and its dependencies (like Eigen via FetchContent) are handled

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Run tests
      run: uv run pytest
